Repository felangel/mason, pull requests merged in 2021-06, with the labels that each got.

#58 fix: windows compatibility issues
  .github/workflows/main.yaml
  bricks/greeting/__brick__/GREETINGS.md
  lib/src/bundler.dart
  lib/src/command.dart
  lib/src/commands/get.dart
  lib/src/commands/make.dart
  lib/src/commands/new.dart
  lib/src/generator.dart
  lib/src/mason_cache.dart
  lib/src/yaml_encode.dart
  pubspec.yaml
  test/commands/bundle_test.dart
  test/commands/get_test.dart
  test/commands/make_test.dart
  test/fixtures/bundle/dart/greeting_bundle.dart
  test/fixtures/bundle/universal/greeting.bundle
  test/fixtures/make/greeting/GREETINGS.md
  test/helpers/directories_deep_equal.dart
Labels: bug, wip

#61 docs: update mason.yaml from init to use https for git
  lib/src/commands/init.dart
  test/fixtures/init/mason.yaml
Labels: documentation

#62 docs: update mustache manual link
  README.md
Labels: documentation

#63 feat: global templates
  .github/workflows/main.yaml
  README.md
  lib/src/command.dart
  lib/src/command_runner.dart
  lib/src/commands/cache.dart
  lib/src/commands/commands.dart
  lib/src/commands/get.dart
  lib/src/commands/install.dart
  lib/src/commands/new.dart
  lib/src/generator.dart
  lib/src/mason_cache.dart
  lib/src/mason_yaml.dart
  test/command_runner_test.dart
  test/commands/get_test.dart
  test/commands/install_test.dart
  test/commands/make_test.dart
  test/fixtures/install/greeting/GREETINGS.md
  test/fixtures/install/widget/cat.dart
Labels: enhancement, refactor

#64 chore: v0.0.1-dev.33
  CHANGELOG.md
  lib/src/version.dart
  pubspec.yaml
Labels: chore

#65 fix: always attempt to fetch latest remote brick
  lib/src/commands/get.dart
  lib/src/mason_cache.dart
  test/commands/get_test.dart
Labels: bug

#66 chore: v0.0.1-dev.34
  CHANGELOG.md
  lib/src/version.dart
  pubspec.yaml
Labels: chore

#67 fix: mason cache clear --force target
  lib/src/mason_cache.dart
  test/commands/cache_test.dart
Labels: bug

#68 chore: v0.0.1-dev.35
  CHANGELOG.md
  lib/src/version.dart
  pubspec.yaml
Labels: chore

#69 feat: add uninstall command
  README.md
  lib/src/command_runner.dart
  lib/src/commands/commands.dart
  lib/src/commands/uninstall.dart
  lib/src/mason_cache.dart
  test/command_runner_test.dart
  test/commands/get_test.dart
  test/commands/uninstall_test.dart
Labels: enhancement

#70 chore: v0.0.1-dev.36
  CHANGELOG.md
  lib/src/version.dart
  pubspec.yaml
Labels: chore

#71 feat: add list command
  README.md
  lib/src/command_runner.dart
  lib/src/commands/bundle.dart
  lib/src/commands/cache.dart
  lib/src/commands/commands.dart
  lib/src/commands/install.dart
  lib/src/commands/list.dart
  lib/src/commands/uninstall.dart
  lib/src/mason_cache.dart
  test/command_runner_test.dart
  test/commands/list_test.dart
Labels: enhancement

#72 chore: v0.0.1-dev.37
  CHANGELOG.md
  lib/src/version.dart
  pubspec.yaml
Labels: chore

#74 feat!: v0.0.1-dev.38
  CHANGELOG.md
  lib/mason.dart
  lib/src/brick_yaml.dart
  lib/src/bricks_json.dart
  lib/src/command.dart
  lib/src/commands/cache.dart
  lib/src/commands/get.dart
  lib/src/commands/install.dart
  lib/src/commands/new.dart
  lib/src/commands/uninstall.dart
  lib/src/generator.dart
  lib/src/mason_yaml.dart
  lib/src/version.dart
  pubspec.yaml
  test/commands/cache_test.dart
  test/commands/get_test.dart
  test/commands/list_test.dart
  test/commands/new_test.dart
  test/commands/uninstall_test.dart
Labels: refactor

#77 feat!: update mason bundle output directory option
  README.md
  lib/src/commands/bundle.dart
Labels: enhancement

#78 feat!: update mason make command to support a custom output directory
  README.md
  example/README.md
  lib/src/commands/make.dart
  test/commands/make_test.dart
  test/fixtures/make/output_dir/dir/GREETINGS.md
Labels: enhancement

#79 chore: v0.0.1-dev.39
  CHANGELOG.md
  lib/src/version.dart
  pubspec.yaml
Labels: chore

#80 fix: create target directory if not existent
  lib/src/generator.dart
  test/commands/make_test.dart
Labels: bug

#81 chore: v0.0.1-dev.40
  CHANGELOG.md
  lib/src/version.dart
  pubspec.yaml
Labels: chore

#82 feat: add `OverwriteRule` to handle file conflicts
  lib/src/commands/make.dart
  lib/src/generator.dart
  lib/src/logger.dart
Labels: enhancement

#83 chore: v0.0.1-dev.41
  CHANGELOG.md
  lib/src/version.dart
  pubspec.yaml
Labels: chore

#84 docs: fix typo in CHANGELOG
  CHANGELOG.md
Labels: documentation

#88 fix: improve mason make --help
  lib/src/commands/make.dart
  test/command_runner_test.dart
  test/commands/make_test.dart
  test/helpers/helpers.dart
  test/helpers/override_print.dart
Labels: bug

#89 chore: v0.0.1-dev.42
  CHANGELOG.md
  lib/src/version.dart
  pubspec.yaml
Labels: chore

#93 feat: support partials
  README.md
  bricks/hello_world/__brick__/HELLO.md
  bricks/hello_world/__brick__/{{~ footer.md }}
  bricks/hello_world/__brick__/{{~ header.md }}
  bricks/hello_world/brick.yaml
  example/mason.yaml
  lib/src/generator.dart
  lib/src/render.dart
  test/commands/make_test.dart
  test/fixtures/make/hello_world/HELLO.md
  test/fixtures/make/mason.yaml
Labels: enhancement

#94 chore: v0.0.1-dev.43
  CHANGELOG.md
  README.md
  lib/src/version.dart
  pubspec.yaml
Labels: chore
