Repository felangel/mason, pull requests merged in 2021-09, with the labels that each got.

#117 refactor: organize imports
  .github/workflows/main.yaml
  lib/src/commands/make.dart
  test/command_runner_test.dart
  test/commands/get_test.dart
  test/commands/list_test.dart
  test/commands/uninstall_test.dart
Labels: refactor

#116 docs: add built-in lambdas section to README
  README.md
Labels: documentation

#121 chore: add PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#120 feat: add append option
  README.md
  lib/src/commands/make.dart
  lib/src/generator.dart
  test/commands/make_test.dart
Labels: enhancement

#124 fix: mason get ensures brick exists
  lib/src/bricks_json.dart
  lib/src/command_runner.dart
  lib/src/commands/get.dart
  test/commands/cache_test.dart
  test/commands/get_test.dart
Labels: bug

#125 refactor: use existsSync consistently
  lib/src/bricks_json.dart
Labels: refactor

#126 refactor: adjust append conflict resolution output
  lib/src/generator.dart
  test/commands/make_test.dart
Labels: refactor

#127 chore: v0.0.1-dev.48
  CHANGELOG.md
  lib/src/version.dart
  pubspec.yaml
Labels: chore

#128 refactor: remove dart:io platform dependency
  .github/workflows/main.yaml
  lib/src/bricks_json.dart
  lib/src/bundler.dart
  lib/src/command.dart
  lib/src/command_runner.dart
  lib/src/commands/bundle.dart
  lib/src/commands/cache.dart
  lib/src/commands/get.dart
  lib/src/commands/init.dart
  lib/src/commands/install.dart
  lib/src/commands/list.dart
  lib/src/commands/make.dart
  lib/src/commands/new.dart
  lib/src/commands/uninstall.dart
  lib/src/generator.dart
  lib/src/git.dart
  lib/src/io.dart
  lib/src/logger.dart
  lib/src/mason_yaml.dart
  pubspec.yaml
  test/command_runner_test.dart
  test/commands/bundle_test.dart
  test/commands/cache_test.dart
  test/commands/get_test.dart
  test/commands/init_test.dart
  test/commands/install_test.dart
  test/commands/list_test.dart
  test/commands/make_test.dart
  test/commands/new_test.dart
  test/commands/uninstall_test.dart
  test/helpers/directories_deep_equal.dart
  test/helpers/set_up_testing_environment.dart
Labels: refactor

#129 chore: v0.0.1-dev.49
  CHANGELOG.md
  lib/src/version.dart
  pubspec.yaml
Labels: chore

#130 feat: mason get improve output and command description
  lib/src/commands/get.dart
  test/command_runner_test.dart
  test/commands/get_test.dart
Labels: enhancement

#131 feat: init command automatically gets first brick
  lib/src/commands/init.dart
  test/commands/init_test.dart
  test/fixtures/init/.mason/bricks.json
Labels: enhancement

#132 feat: create mason add command
  README.md
  lib/src/command_runner.dart
  lib/src/commands/add.dart
  lib/src/commands/commands.dart
  lib/src/commands/new.dart
  test/command_runner_test.dart
  test/commands/add_test.dart
  test/fixtures/add/greeting/GREETINGS.md
  test/fixtures/add/widget/cat.dart
Labels: enhancement

#133 fix: logger stopwatch units
  lib/src/logger.dart
Labels: bug

#134 feat: improve mason list empty output
  lib/src/commands/list.dart
  test/commands/list_test.dart
Labels: enhancement

#135 feat!: introduce add/remove commands and remove install/uninstall
  README.md
  lib/src/command_runner.dart
  lib/src/commands/add.dart
  lib/src/commands/commands.dart
  lib/src/commands/install.dart
  lib/src/commands/make.dart
  lib/src/commands/remove.dart
  lib/src/commands/uninstall.dart
  test/command_runner_test.dart
  test/commands/add_test.dart
  test/commands/install_test.dart
  test/commands/list_test.dart
  test/commands/make_test.dart
  test/commands/remove_test.dart
  test/commands/uninstall_test.dart
Labels: enhancement, breaking change

#136 feat: adjust mason init generated mason.yaml
  lib/src/commands/init.dart
  test/fixtures/init/mason.yaml
Labels: enhancement

#137 chore: v0.0.1-dev.50
  CHANGELOG.md
  lib/src/version.dart
  pubspec.yaml
Labels: chore

#138 feat: conditional file and directory creation support
  bricks/plugin/__brick__/README.md
  bricks/plugin/__brick__/example/{{#android}}android.dart{{/android}}
  bricks/plugin/__brick__/example/{{#ios}}ios.dart{{/ios}}
  bricks/plugin/__brick__/tests/{{#android}}android_tests.dart{{/android}}
  bricks/plugin/__brick__/tests/{{#ios}}ios_tests.dart{{/ios}}
  bricks/plugin/__brick__/{{#android}}android{{/android}}/README.md
  bricks/plugin/__brick__/{{#android}}build.gradle{{/android}}
  bricks/plugin/__brick__/{{#ios}}Podfile{{/ios}}
  bricks/plugin/__brick__/{{#ios}}ios{{/ios}}/README.md
  bricks/plugin/brick.yaml
  example/mason.yaml
  lib/src/commands/make.dart
  lib/src/generator.dart
  test/commands/make_test.dart
  test/fixtures/make/plugin/android/README.md
  test/fixtures/make/plugin/android/android/README.md
  test/fixtures/make/plugin/android/build.gradle
  test/fixtures/make/plugin/android/example/android.dart
  test/fixtures/make/plugin/android/tests/android_tests.dart
  test/fixtures/make/plugin/android_ios/Podfile
  test/fixtures/make/plugin/android_ios/README.md
  test/fixtures/make/plugin/android_ios/android/README.md
  test/fixtures/make/plugin/android_ios/build.gradle
  test/fixtures/make/plugin/android_ios/example/android.dart
  test/fixtures/make/plugin/android_ios/example/ios.dart
  test/fixtures/make/plugin/android_ios/ios/README.md
  test/fixtures/make/plugin/android_ios/tests/android_tests.dart
  test/fixtures/make/plugin/android_ios/tests/ios_tests.dart
  test/fixtures/make/plugin/empty/README.md
  test/fixtures/make/plugin/ios/Podfile
  test/fixtures/make/plugin/ios/README.md
  test/fixtures/make/plugin/ios/example/ios.dart
  test/fixtures/make/plugin/ios/ios/README.md
  test/fixtures/make/plugin/ios/tests/ios_tests.dart
Labels: enhancement

#139 chore: v0.0.1-dev.51
  CHANGELOG.md
  lib/src/version.dart
  pubspec.yaml
Labels: chore
