Repository felangel/mason, pull requests merged in 2022-02, with the labels that each got.

#221 feat(bundle): apply bzip2 compression
  packages/mason_cli/lib/src/commands/bundle.dart
  packages/mason_cli/pubspec.yaml
  packages/mason_cli/test/commands/bundle_test.dart
Labels: enhancement

#222 chore(mason_cli): v0.1.0-dev.9
  packages/mason_cli/CHANGELOG.md
  packages/mason_cli/lib/src/version.dart
  packages/mason_cli/pubspec.yaml
Labels: chore

#225 feat(mason): return list of GeneratedFile from generate
  .github/workflows/mason_cli.yaml
  packages/mason/lib/mason.dart
  packages/mason/lib/src/generator.dart
  packages/mason/pubspec.yaml
  packages/mason/test/src/generator_test.dart
  packages/mason_cli/lib/src/commands/make.dart
  packages/mason_cli/pubspec.yaml
  packages/mason_cli/test/mason_generator_test.dart
Labels: enhancement, breaking change

#224 feat(mason_cli)!: add --set-exit-if-changed to make command
  packages/mason_cli/README.md
  packages/mason_cli/lib/src/commands/make.dart
  packages/mason_cli/test/commands/make_test.dart
Labels: enhancement, breaking change

#227 chore(mason): v0.1.0-dev.6
  packages/mason/CHANGELOG.md
  packages/mason/lib/src/version.dart
  packages/mason/pubspec.yaml
Labels: chore

#228 chore(mason_cli): upgrade to mason 0.1.0-dev.6
  .github/workflows/mason_cli.yaml
  packages/mason_cli/lib/src/command_runner.dart
  packages/mason_cli/lib/src/commands/update.dart
  packages/mason_cli/pubspec.yaml
  packages/mason_cli/test/commands/add_test.dart
  packages/mason_cli/test/commands/bundle_test.dart
  packages/mason_cli/test/commands/cache_test.dart
  packages/mason_cli/test/commands/get_test.dart
  packages/mason_cli/test/commands/init_test.dart
  packages/mason_cli/test/commands/list_test.dart
  packages/mason_cli/test/commands/make_test.dart
  packages/mason_cli/test/commands/new_test.dart
  packages/mason_cli/test/commands/remove_test.dart
  packages/mason_cli/test/commands/update_test.dart
  packages/mason_cli/test/src/command_runner_test.dart
Labels: chore

#229 chore(mason_cli): v0.1.0-dev.10
  packages/mason_cli/CHANGELOG.md
  packages/mason_cli/lib/src/version.dart
  packages/mason_cli/pubspec.yaml
Labels: chore

#230 ci: upgrade to very_good_coverage@v1
  .github/workflows/mason.yaml
  .github/workflows/mason_cli.yaml
  .github/workflows/mason_logger.yaml
Labels: ci

#231 feat: remote brick download
  .github/workflows/mason_cli.yaml
  packages/mason/CHANGELOG.md
  packages/mason/lib/mason.dart
  packages/mason/lib/src/brick.dart
  packages/mason/lib/src/bricks_json.dart
  packages/mason/lib/src/bundler.dart
  packages/mason/lib/src/generator.dart
  packages/mason/lib/src/mason_bundle.dart
  packages/mason/lib/src/mason_yaml.dart
  packages/mason/lib/src/mason_yaml.g.dart
  packages/mason/lib/src/version.dart
  packages/mason/pubspec.yaml
  packages/mason/test/src/bricks_json_test.dart
  packages/mason/test/src/bundler_test.dart
  packages/mason/test/src/exception_test.dart
  packages/mason/test/src/generator_test.dart
  packages/mason/test/src/mason_bundle_test.dart
  packages/mason/test/src/mason_yaml_test.dart
  packages/mason_cli/CHANGELOG.md
  packages/mason_cli/lib/src/command.dart
  packages/mason_cli/lib/src/commands/add.dart
  packages/mason_cli/lib/src/commands/bundle.dart
  packages/mason_cli/lib/src/commands/get.dart
  packages/mason_cli/lib/src/commands/init.dart
  packages/mason_cli/lib/src/commands/new.dart
  packages/mason_cli/lib/src/commands/remove.dart
  packages/mason_cli/lib/src/version.dart
  packages/mason_cli/pubspec.yaml
  packages/mason_cli/test/commands/bundle_test.dart
  packages/mason_cli/test/commands/get_test.dart
  packages/mason_cli/test/commands/make_test.dart
  packages/mason_cli/test/commands/remove_test.dart
  packages/mason_cli/test/src/command_test.dart
Labels: enhancement, breaking change

#232 refactor(mason)!: simplify bricks.json format
  packages/mason/CHANGELOG.md
  packages/mason/lib/src/bricks_json.dart
  packages/mason/test/src/bricks_json_test.dart
  packages/mason_cli/test/commands/get_test.dart
  packages/mason_cli/test/commands/make_test.dart
  packages/mason_cli/test/commands/remove_test.dart
Labels: refactor, breaking change

#233 refactor(mason): Brick.path requires brick name
  packages/mason/lib/src/brick.dart
  packages/mason/test/src/bricks_json_test.dart
  packages/mason_cli/lib/src/commands/add.dart
  packages/mason_cli/lib/src/commands/new.dart
Labels: refactor

#234 refactor(mason): make brick name optional in Brick class
  packages/mason/lib/src/brick.dart
  packages/mason/lib/src/bricks_json.dart
  packages/mason/test/src/bricks_json_test.dart
  packages/mason_cli/lib/src/commands/add.dart
  packages/mason_cli/lib/src/commands/new.dart
Labels: refactor

#235 feat(mason_cli)!: mason add support for hosted bricks
  packages/mason/CHANGELOG.md
  packages/mason/lib/src/bricks_json.dart
  packages/mason/test/src/bricks_json_test.dart
  packages/mason_cli/CHANGELOG.md
  packages/mason_cli/README.md
  packages/mason_cli/lib/src/commands/add.dart
  packages/mason_cli/lib/src/yaml_encode.dart
  packages/mason_cli/test/commands/add_test.dart
  packages/mason_cli/test/commands/list_test.dart
  packages/mason_cli/test/commands/remove_test.dart
  packages/mason_cli/test/src/yaml_encode_test.dart
Labels: enhancement, breaking change

#236 refactor(mason)!: MasonGenerator.fromBrick
  packages/mason/CHANGELOG.md
  packages/mason/README.md
  packages/mason/example/main.dart
  packages/mason/lib/src/generator.dart
  packages/mason/test/src/generator_test.dart
  packages/mason/test/src/hooks_test.dart
  packages/mason_cli/lib/src/commands/make.dart
Labels: refactor, breaking change

#238 feat(mason_auth): create package:mason_auth
  .github/workflows/mason_auth.yaml
  packages/mason_auth/.gitignore
  packages/mason_auth/CHANGELOG.md
  packages/mason_auth/LICENSE
  packages/mason_auth/README.md
  packages/mason_auth/analysis_options.yaml
  packages/mason_auth/build.yaml
  packages/mason_auth/coverage_badge.svg
  packages/mason_auth/example/main.dart
  packages/mason_auth/lib/mason_auth.dart
  packages/mason_auth/lib/src/jwt_decode.dart
  packages/mason_auth/lib/src/mason_auth.dart
  packages/mason_auth/lib/src/models/credentials.dart
  packages/mason_auth/lib/src/models/credentials.g.dart
  packages/mason_auth/lib/src/models/models.dart
  packages/mason_auth/lib/src/models/user.dart
  packages/mason_auth/pubspec.yaml
  packages/mason_auth/test/src/jwt_decode_test.dart
  packages/mason_auth/test/src/mason_auth_test.dart
Labels: enhancement

#239 feat(mason_logger): add hidden flag to prompt
  packages/mason_logger/lib/src/mason_logger.dart
  packages/mason_logger/test/src/mason_logger_test.dart
Labels: enhancement

#240 feat(mason_cli): add mason login command
  packages/mason_cli/lib/src/command_runner.dart
  packages/mason_cli/lib/src/commands/commands.dart
  packages/mason_cli/lib/src/commands/login.dart
  packages/mason_cli/pubspec.yaml
  packages/mason_cli/test/commands/login_test.dart
  packages/mason_cli/test/src/command_runner_test.dart
Labels: enhancement

#241 feat(mason_cli): add mason logout command
  packages/mason_cli/lib/src/command_runner.dart
  packages/mason_cli/lib/src/commands/commands.dart
  packages/mason_cli/lib/src/commands/logout.dart
  packages/mason_cli/test/commands/login_test.dart
  packages/mason_cli/test/commands/logout_test.dart
  packages/mason_cli/test/src/command_runner_test.dart
Labels: enhancement

#242 refactor(mason): convert hostedUrl to hostedUri
  packages/mason/lib/src/bricks_json.dart
  packages/mason/test/src/bricks_json_test.dart
Labels: refactor

#243 refactor(mason): refactor git cache directory location
  packages/mason/lib/src/bricks_json.dart
Labels: refactor

#244 feat(mason_cli): add brick source to mason list
  packages/mason/lib/mason.dart
  packages/mason/lib/src/bricks_json.dart
  packages/mason/lib/src/path.dart
  packages/mason_cli/lib/src/commands/bundle.dart
  packages/mason_cli/lib/src/commands/list.dart
  packages/mason_cli/lib/src/commands/make.dart
  packages/mason_cli/test/commands/add_test.dart
  packages/mason_cli/test/commands/bundle_test.dart
  packages/mason_cli/test/commands/get_test.dart
  packages/mason_cli/test/commands/list_test.dart
  packages/mason_cli/test/commands/make_test.dart
  packages/mason_cli/test/commands/remove_test.dart
Labels: enhancement

#245 fix(mason_cli): simplify update prompt styling
  packages/mason_cli/lib/src/command_runner.dart
  packages/mason_cli/test/src/command_runner_test.dart
Labels: bug

#246 feat(mason_auth): add publish
  packages/mason_auth/lib/mason_auth.dart
  packages/mason_auth/lib/src/mason_auth.dart
  packages/mason_auth/test/src/mason_auth_test.dart
Labels: enhancement

#247 feat(mason_api): create package:mason_api
  .github/workflows/mason_api.yaml
  README.md
  packages/mason_api/.gitignore
  packages/mason_api/CHANGELOG.md
  packages/mason_api/LICENSE
  packages/mason_api/README.md
  packages/mason_api/analysis_options.yaml
  packages/mason_api/build.yaml
  packages/mason_api/coverage_badge.svg
  packages/mason_api/example/main.dart
  packages/mason_api/lib/mason_api.dart
  packages/mason_api/lib/src/jwt_decode.dart
  packages/mason_api/lib/src/mason_api.dart
  packages/mason_api/lib/src/models/credentials.dart
  packages/mason_api/lib/src/models/credentials.g.dart
  packages/mason_api/lib/src/models/models.dart
  packages/mason_api/lib/src/models/user.dart
  packages/mason_api/pubspec.yaml
  packages/mason_api/test/src/jwt_decode_test.dart
  packages/mason_api/test/src/mason_api_test.dart
  packages/mason_auth/CHANGELOG.md
  packages/mason_auth/README.md
  packages/mason_auth/example/main.dart
  packages/mason_auth/lib/mason_auth.dart
  packages/mason_cli/lib/src/command_runner.dart
  packages/mason_cli/lib/src/commands/login.dart
  packages/mason_cli/lib/src/commands/logout.dart
  packages/mason_cli/pubspec.yaml
  packages/mason_cli/test/commands/login_test.dart
  packages/mason_cli/test/commands/logout_test.dart
Labels: enhancement

#248 feat(mason_cli): add mason publish
  packages/mason_cli/README.md
  packages/mason_cli/lib/src/command_runner.dart
  packages/mason_cli/lib/src/commands/commands.dart
  packages/mason_cli/lib/src/commands/publish.dart
  packages/mason_cli/test/commands/make_test.dart
  packages/mason_cli/test/commands/publish_test.dart
  packages/mason_cli/test/helpers/set_up_testing_environment.dart
  packages/mason_cli/test/src/command_runner_test.dart
Labels: enhancement

#249 feat(mason_api): support custom hosted uri
  packages/mason_api/lib/src/mason_api.dart
  packages/mason_api/test/src/mason_api_test.dart
Labels: enhancement

#250 refactor(mason_cli): use hosted uri
  packages/mason_cli/lib/src/command_runner.dart
Labels: refactor

#251 chore(mason_api): v0.1.0-dev.2
  packages/mason_api/CHANGELOG.md
  packages/mason_api/pubspec.yaml
Labels: chore

#252 feat(mason_cli): add publish prompt/alert
  packages/mason_cli/lib/src/commands/publish.dart
  packages/mason_cli/test/commands/publish_test.dart
Labels: enhancement

#253 chore(mason_logger): upgrade to Dart 2.16
  .github/workflows/mason_logger.yaml
  packages/mason_logger/pubspec.yaml
Labels: chore

#254 chore(mason_api): upgrade to Dart 2.16
  .github/workflows/mason_api.yaml
  packages/mason_api/pubspec.yaml
  packages/mason_api/test/src/mason_api_test.dart
Labels: chore

#255 chore(mason): upgrade to Dart 2.16
  .github/workflows/mason.yaml
  packages/mason/lib/src/generator.dart
  packages/mason/pubspec.yaml
Labels: chore

#256 chore(mason_cli): upgrade to Dart 2.16
  .github/workflows/mason_cli.yaml
  packages/mason_cli/pubspec.yaml
  packages/mason_cli/test/commands/login_test.dart
  packages/mason_cli/test/commands/logout_test.dart
  packages/mason_cli/test/commands/publish_test.dart
Labels: chore

#257 refactor(mason)!: MasonBundle.toUniversalBundle run in Isolate
  packages/mason/lib/src/compute.dart
  packages/mason/lib/src/mason_bundle.dart
  packages/mason/test/src/compute_test.dart
  packages/mason/test/src/mason_bundle_test.dart
Labels: refactor, breaking change

#258 refactor(mason_cli): use async toUniversalBundle
  packages/mason_cli/lib/src/commands/bundle.dart
  packages/mason_cli/lib/src/commands/publish.dart
Labels: refactor

#259 feat(mason_cli): verify bundle size before publish
  packages/mason_cli/lib/src/command.dart
  packages/mason_cli/lib/src/commands/publish.dart
  packages/mason_cli/pubspec.yaml
  packages/mason_cli/test/commands/publish_test.dart
Labels: enhancement

#260 chore(mason_api): v0.1.0-dev.3
  packages/mason_api/CHANGELOG.md
  packages/mason_api/pubspec.yaml
Labels: chore

#261 chore(mason_logger): v0.1.0-dev.5
  packages/mason_logger/CHANGELOG.md
  packages/mason_logger/pubspec.yaml
Labels: chore

#262 chore(mason): v0.1.0-dev.7
  packages/mason/CHANGELOG.md
  packages/mason/pubspec.yaml
Labels: chore

#263 chore(mason_cli): v0.1.0-dev.11
  packages/mason_cli/CHANGELOG.md
  packages/mason_cli/README.md
  packages/mason_cli/pubspec.yaml
Labels: chore

#264 feat(mason): add environment to brick.yaml
  packages/mason/lib/mason.dart
  packages/mason/lib/src/brick_yaml.dart
  packages/mason/lib/src/brick_yaml.g.dart
  packages/mason/lib/src/bundler.dart
  packages/mason/lib/src/mason_bundle.dart
  packages/mason/lib/src/mason_bundle.g.dart
  packages/mason/test/src/bundler_test.dart
  packages/mason/test/src/mason_bundle_test.dart
Labels: enhancement

#266 feat(mason_cli): support brick environment
  packages/mason_cli/lib/src/commands/init.dart
  packages/mason_cli/lib/src/commands/new.dart
  packages/mason_cli/test/commands/bundle_test.dart
  packages/mason_cli/test/commands/publish_test.dart
  packages/mason_cli/test/fixtures/init/bricks/hello/brick.yaml
  packages/mason_cli/test/fixtures/new/bricks/hello_world/brick.yaml
Labels: enhancement

#267 feat(mason_cli): mason make verify brick supports current mason version
  packages/mason_cli/lib/src/commands/make.dart
  packages/mason_cli/pubspec.yaml
  packages/mason_cli/test/commands/make_test.dart
Labels: enhancement

#268 feat(mason): add isBrickCompatibleWithMason
  packages/mason/lib/mason.dart
  packages/mason/lib/src/brick_compatibility.dart
  packages/mason/lib/src/bricks_json.dart
  packages/mason/test/src/brick_compatibility_test.dart
  packages/mason/test/src/bricks_json_test.dart
  packages/mason_cli/lib/src/commands/make.dart
  packages/mason_cli/pubspec.yaml
  packages/mason_cli/test/commands/get_test.dart
  packages/mason_cli/test/commands/make_test.dart
Labels: enhancement

#269 chore(mason): v0.1.0-dev.8
  packages/mason/CHANGELOG.md
  packages/mason/lib/src/version.dart
  packages/mason/pubspec.yaml
Labels: chore

#270 chore(mason_cli): v0.1.0-dev.12
  .github/workflows/mason_cli.yaml
  packages/mason_cli/CHANGELOG.md
  packages/mason_cli/lib/src/version.dart
  packages/mason_cli/pubspec.yaml
Labels: chore

#271 fix(mason_cli): mason list git path parsing
  packages/mason_cli/lib/src/commands/list.dart
  packages/mason_cli/test/commands/list_test.dart
Labels: bug

#272 feat(mason_cli): improve stdout for mason bundle
  packages/mason_cli/lib/src/commands/bundle.dart
  packages/mason_cli/test/commands/bundle_test.dart
Labels: enhancement

#273 chore(mason_cli): v0.1.0-dev.13
  packages/mason_cli/CHANGELOG.md
  packages/mason_cli/lib/src/version.dart
  packages/mason_cli/pubspec.yaml
Labels: chore

#274 feat: expose MasonBundledFile
  packages/mason/lib/mason.dart
  packages/mason/lib/src/bundler.dart
  packages/mason/lib/src/generator.dart
  packages/mason/test/src/mason_bundle_test.dart
Labels: enhancement

#275 chore(mason): v0.1.0-dev.9
  packages/mason/CHANGELOG.md
  packages/mason/lib/src/version.dart
  packages/mason/pubspec.yaml
Labels: chore

#277 feat: add `mason unbundle` command
  .github/workflows/mason_cli.yaml
  packages/mason/lib/src/mason_bundle.dart
  packages/mason/test/src/mason_bundle_test.dart
  packages/mason_cli/README.md
  packages/mason_cli/lib/src/command_runner.dart
  packages/mason_cli/lib/src/commands/commands.dart
  packages/mason_cli/lib/src/commands/unbundle.dart
  packages/mason_cli/test/bundles/greeting.bundle
  packages/mason_cli/test/bundles/greeting_bundle.dart
  packages/mason_cli/test/commands/unbundle_test.dart
  packages/mason_cli/test/fixtures/unbundle/__brick__/GREETINGS.md
  packages/mason_cli/test/fixtures/unbundle/brick.yaml
  packages/mason_cli/test/src/command_runner_test.dart
Labels: enhancement

#278 docs(mason_cli): update unbundle docs in README
  packages/mason_cli/README.md
Labels: documentation

#279 feat(mason)!: use async fromUniversalBundle
  packages/mason/lib/src/bricks_json.dart
  packages/mason/lib/src/mason_bundle.dart
  packages/mason/test/src/mason_bundle_test.dart
  packages/mason_cli/test/commands/bundle_test.dart
Labels: enhancement, breaking change
