Repository felangel/mason, pull requests merged in 2022-03, with the labels that each got.

#281 chore(mason): v0.1.0-dev.10
  packages/mason/CHANGELOG.md
  packages/mason/lib/src/version.dart
  packages/mason/pubspec.yaml
Labels: chore

#283 fix(mason): yaml.encode handle escape characters
  packages/mason/lib/src/yaml_encode.dart
  packages/mason/test/src/yaml_encode_test.dart
Labels: bug

#284 chore(mason): v0.1.0-dev.11
  packages/mason/CHANGELOG.md
  packages/mason/lib/src/version.dart
  packages/mason/pubspec.yaml
Labels: chore

#285 feat(mason_cli): mason new include README, CHANGELOG, and LICENSE
  packages/mason_cli/lib/src/commands/new.dart
  packages/mason_cli/test/fixtures/new/bricks/hello_world/CHANGELOG.md
  packages/mason_cli/test/fixtures/new/bricks/hello_world/LICENSE
  packages/mason_cli/test/fixtures/new/bricks/hello_world/README.md
Labels: enhancement

#286 feat(mason_cli): add inline comments to new brick.yaml
  packages/mason_cli/lib/src/commands/new.dart
  packages/mason_cli/test/fixtures/new/bricks/hello_world/brick.yaml
Labels: enhancement

#287 refactor(mason_cli): adjust mason new generated file name
  packages/mason_cli/lib/src/commands/new.dart
  packages/mason_cli/test/fixtures/new/bricks/hello_world/__brick__/HELLO.md
Labels: refactor

#288 feat(mason_cli): mason init only generate mason.yaml
  packages/mason_cli/lib/src/commands/init.dart
  packages/mason_cli/test/fixtures/init/bricks/hello/__brick__/HELLO.md
  packages/mason_cli/test/fixtures/init/bricks/hello/brick.yaml
  packages/mason_cli/test/fixtures/init/mason.yaml
Labels: enhancement

#289 feat(mason_cli)!: mason new only generates new brick w/custom output-dir
  packages/mason_cli/lib/src/commands/new.dart
  packages/mason_cli/test/commands/get_test.dart
  packages/mason_cli/test/commands/make_test.dart
  packages/mason_cli/test/commands/new_test.dart
  packages/mason_cli/test/fixtures/new/.mason/bricks.json
  packages/mason_cli/test/fixtures/new/custom/bricks/hello_world/CHANGELOG.md
  packages/mason_cli/test/fixtures/new/custom/bricks/hello_world/LICENSE
  packages/mason_cli/test/fixtures/new/custom/bricks/hello_world/README.md
  packages/mason_cli/test/fixtures/new/custom/bricks/hello_world/__brick__/HELLO.md
  packages/mason_cli/test/fixtures/new/custom/bricks/hello_world/brick.yaml
  packages/mason_cli/test/fixtures/new/mason.yaml
  packages/mason_cli/test/fixtures/new/simple/hello_world/CHANGELOG.md
  packages/mason_cli/test/fixtures/new/simple/hello_world/LICENSE
  packages/mason_cli/test/fixtures/new/simple/hello_world/README.md
  packages/mason_cli/test/fixtures/new/simple/hello_world/__brick__/HELLO.md
  packages/mason_cli/test/fixtures/new/simple/hello_world/brick.yaml
Labels: enhancement, breaking change

#291 chore(mason_cli): v0.1.0-dev.15
  packages/mason_cli/CHANGELOG.md
  packages/mason_cli/lib/src/version.dart
  packages/mason_cli/pubspec.yaml
Labels: chore

#292 feat(mason): include README, CHANGELOG, and LICENSE in MasonBundle
  bricks/hello/CHANGELOG.md
  bricks/hello/LICENSE
  bricks/hello/README.md
  packages/mason/lib/src/bundler.dart
  packages/mason/lib/src/mason_bundle.dart
  packages/mason/lib/src/mason_bundle.g.dart
  packages/mason/test/src/bundler_test.dart
  packages/mason/test/src/mason_bundle_test.dart
Labels: enhancement

#293 chore(mason): v0.1.0-dev.12
  packages/mason/CHANGELOG.md
  packages/mason/lib/src/version.dart
  packages/mason/pubspec.yaml
Labels: chore

#295 chore(mason_logger): v0.1.0-dev.6
  packages/mason_logger/CHANGELOG.md
  packages/mason_logger/pubspec.yaml
Labels: chore

#296 feat(mason_api): add details to MasonApiException
  packages/mason_api/lib/src/mason_api.dart
  packages/mason_api/test/src/mason_api_test.dart
Labels: enhancement

#297 refactor(mason_api): define ErrorResponse w/JsonSerializable
  packages/mason_api/lib/src/mason_api.dart
  packages/mason_api/lib/src/models/error_response.dart
  packages/mason_api/lib/src/models/error_response.g.dart
  packages/mason_api/lib/src/models/models.dart
  packages/mason_api/test/src/mason_api_test.dart
Labels: refactor

#298 chore(mason_api): v0.1.0-dev.4
  packages/mason_api/CHANGELOG.md
  packages/mason_api/pubspec.yaml
Labels: chore

#299 feat(mason_cli): upgrade to mason_api v0.1.0-dev.4
  packages/mason_cli/lib/src/commands/publish.dart
  packages/mason_cli/pubspec.yaml
  packages/mason_cli/test/commands/publish_test.dart
Labels: enhancement

#300 chore(mason_cli): v0.1.0-dev.16
  packages/mason_cli/CHANGELOG.md
  packages/mason_cli/lib/src/version.dart
  packages/mason_cli/pubspec.yaml
Labels: chore

#301 chore: add README, CHANGELOG, LICENSE to greeting
  bricks/greeting/CHANGELOG.md
  bricks/greeting/LICENSE
  bricks/greeting/README.md
  packages/mason_cli/test/commands/bundle_test.dart
  packages/mason_cli/test/commands/publish_test.dart
Labels: chore

#302 chore(mason_cli): use fixed version of hello brick in mason init
  packages/mason_cli/lib/src/commands/init.dart
  packages/mason_cli/test/fixtures/init/mason.yaml
Labels: chore

#303 chore(mason_cli): v0.1.0-dev.17
  packages/mason_cli/CHANGELOG.md
  packages/mason_cli/lib/src/version.dart
  packages/mason_cli/pubspec.yaml
Labels: chore

#305 feat(mason)!: add MasonLockJson
  packages/mason/lib/mason.dart
  packages/mason/lib/src/brick_compatibility.dart
  packages/mason/lib/src/bricks_json.dart
  packages/mason/lib/src/generator.dart
  packages/mason/lib/src/mason_lock_json.dart
  packages/mason/lib/src/mason_lock_json.g.dart
  packages/mason/test/src/bricks_json_test.dart
  packages/mason/test/src/mason_lock_json_test.dart
Labels: enhancement, breaking change

#307 chore(mason): expose GeneratorHooks
  packages/mason/lib/mason.dart
Labels: chore

#306 feat(mason_cli): mason-lock.json
  .github/workflows/mason_cli.yaml
  packages/mason/lib/src/mason_lock_json.dart
  packages/mason_cli/.gitignore
  packages/mason_cli/lib/src/command.dart
  packages/mason_cli/lib/src/commands/add.dart
  packages/mason_cli/lib/src/commands/get.dart
  packages/mason_cli/lib/src/commands/init.dart
  packages/mason_cli/lib/src/commands/remove.dart
  packages/mason_cli/lib/src/install_brick.dart
  packages/mason_cli/test/commands/get_test.dart
  packages/mason_cli/test/commands/init_test.dart
  packages/mason_cli/test/fixtures/init/mason-lock.json
  packages/mason_cli/test/src/install_brick_test.dart
Labels: enhancement

#312 chore(mason_cli): v0.1.0-dev.18
  .github/workflows/mason_cli.yaml
  packages/mason_cli/CHANGELOG.md
  packages/mason_cli/lib/src/version.dart
  packages/mason_cli/pubspec.yaml
Labels: chore

#315 fix(mason_logger): multiline prompts are outputting twice
  packages/mason_logger/lib/src/mason_logger.dart
  packages/mason_logger/test/src/mason_logger_test.dart
Labels: bug

#316 chore(mason_logger): v0.1.0-dev.7
  packages/mason_logger/CHANGELOG.md
  packages/mason_logger/pubspec.yaml
Labels: chore
