Repository felangel/mason, pull requests merged in 2022-12, with the labels that each got.

#653 fix(vscode): git url schema validation
  extensions/vscode/schema/mason.yaml.schema.json
Labels: bug

#654 chore(vscode): v0.1.7
  extensions/vscode/CHANGELOG.md
  extensions/vscode/package-lock.json
  extensions/vscode/package.json
Labels: chore

#660 feat(mason_cli): add completion
  packages/mason_cli/lib/src/command_runner.dart
  packages/mason_cli/pubspec.yaml
  packages/mason_cli/test/src/command_runner_test.dart
Labels: enhancement

#661 chore(mason_cli): v0.1.0-dev.41
  packages/mason_cli/CHANGELOG.md
  packages/mason_cli/lib/src/version.dart
  packages/mason_cli/pubspec.yaml
Labels: chore

#677 feat(mason_cli): improve error when running add in an uninitialized directory
  packages/mason_cli/lib/src/install_brick.dart
  packages/mason_cli/test/commands/add_test.dart
Labels: enhancement

#678 feat(mason_cli): search separator length uses terminalColumns
  packages/mason_cli/lib/src/commands/search.dart
  packages/mason_cli/test/commands/search_test.dart
Labels: enhancement

#679 feat(mason): export StringCaseExtensions
  .github/workflows/mason_cli.yaml
  packages/mason/lib/mason.dart
  packages/mason/lib/src/render.dart
  packages/mason/lib/src/string_case_extensions.dart
  packages/mason_cli/lib/src/commands/bundle.dart
  packages/mason_cli/lib/src/commands/new.dart
  packages/mason_cli/pubspec.yaml
Labels: enhancement

#680 chore(mason): v0.1.0-dev.40
  packages/mason/CHANGELOG.md
  packages/mason/lib/src/version.dart
  packages/mason/pubspec.yaml
  packages/mason_cli/test/fixtures/new/custom/bricks/hello_world/brick.yaml
  packages/mason_cli/test/fixtures/new/hooks/brick.yaml
  packages/mason_cli/test/fixtures/new/hooks/hooks/pubspec.yaml
  packages/mason_cli/test/fixtures/new/simple/hello_world/brick.yaml
Labels: chore

#681 chore(mason_cli): v0.1.0-dev.42
  .github/workflows/mason_cli.yaml
  packages/mason_cli/CHANGELOG.md
  packages/mason_cli/lib/src/version.dart
  packages/mason_cli/pubspec.yaml
Labels: chore
