Repository felangel/mason, pull requests merged in 2022-09, with the labels that each got.

#512 ci: remove deprecated .packages
  .github/workflows/mason.yaml
  .github/workflows/mason_api.yaml
  .github/workflows/mason_cli.yaml
  .github/workflows/mason_logger.yaml
  packages/mason/lib/src/compute.dart
Labels: ci

#511 fix(mason): use file descriptor pooling
  .github/workflows/mason.yaml
  .github/workflows/mason_cli.yaml
  packages/mason/lib/src/generator.dart
  packages/mason/pubspec.yaml
  packages/mason/test/src/generator_test.dart
Labels: bug

#513 chore(mason): v0.1.0-dev.32
  packages/mason/CHANGELOG.md
  packages/mason/README.md
  packages/mason/lib/src/version.dart
  packages/mason/pubspec.yaml
Labels: chore

#517 feat(logger): add `link`
  packages/mason_logger/example/main.dart
  packages/mason_logger/lib/mason_logger.dart
  packages/mason_logger/lib/src/link.dart
  packages/mason_logger/test/src/link_test.dart
Labels: enhancement

#521 chore(mason_logger): v0.1.3
  packages/mason_logger/CHANGELOG.md
  packages/mason_logger/README.md
  packages/mason_logger/pubspec.yaml
Labels: chore

#518 fix(mason_cli): upgrade from subdirectory w/relative paths
  packages/mason_cli/lib/src/install_brick.dart
  packages/mason_cli/test/commands/get_test.dart
  packages/mason_cli/test/commands/upgrade_test.dart
Labels: bug

#519 fix(mason_cli): add from subdirectory w/relative path
  packages/mason_cli/lib/src/commands/add.dart
  packages/mason_cli/test/commands/add_test.dart
Labels: bug

#522 chore(mason): v0.1.0-dev.33
  packages/mason/CHANGELOG.md
  packages/mason/lib/src/version.dart
  packages/mason/pubspec.yaml
Labels: chore

#523 feat(mason_cli): use logger link api
  packages/mason_cli/lib/src/command_runner.dart
  packages/mason_cli/lib/src/commands/publish.dart
  packages/mason_cli/lib/src/commands/search.dart
  packages/mason_cli/pubspec.yaml
  packages/mason_cli/test/commands/publish_test.dart
  packages/mason_cli/test/src/command_runner_test.dart
Labels: enhancement

#524 chore(mason_cli): v0.1.0-dev.35
  packages/mason_cli/CHANGELOG.md
  packages/mason_cli/lib/src/version.dart
  packages/mason_cli/pubspec.yaml
Labels: chore
