Repository felangel/mason, pull requests merged in 2022-04, with the labels that each got.

#319 feat(mason): add optional repository field to brick.yaml
  bricks/greeting/brick.yaml
  bricks/hello/brick.yaml
  packages/mason/lib/src/brick_yaml.dart
  packages/mason/lib/src/brick_yaml.g.dart
  packages/mason/lib/src/bundler.dart
  packages/mason/lib/src/mason_bundle.dart
  packages/mason/lib/src/mason_bundle.g.dart
  packages/mason/test/src/brick_yaml_test.dart
  packages/mason/test/src/bundler_test.dart
  packages/mason/test/src/mason_bundle_test.dart
Labels: enhancement

#320 chore(mason): v0.1.0-dev.14
  packages/mason/CHANGELOG.md
  packages/mason/lib/src/version.dart
  packages/mason/pubspec.yaml
Labels: chore

#321 chore(mason_cli): add policy details on publish
  packages/mason_cli/lib/src/commands/publish.dart
  packages/mason_cli/test/commands/publish_test.dart
Labels: chore

#322 chore(mason_cli): v0.1.0-dev.19
  packages/mason_cli/CHANGELOG.md
  packages/mason_cli/lib/src/version.dart
  packages/mason_cli/pubspec.yaml
Labels: chore

#326 chore(mason_cli): v0.1.0-dev.20
  packages/mason_cli/CHANGELOG.md
  packages/mason_cli/lib/src/version.dart
  packages/mason_cli/pubspec.yaml
Labels: chore

#327 fix(mason_logger): previous line overwrite on single-line prompts
  packages/mason_logger/lib/src/mason_logger.dart
  packages/mason_logger/test/src/mason_logger_test.dart
Labels: bug

#328 chore(mason_logger): v0.1.0-dev.8
  packages/mason_logger/CHANGELOG.md
  packages/mason_logger/pubspec.yaml
Labels: chore

#330 feat(mason_cli): mason new --hooks
  packages/mason_cli/lib/src/commands/new.dart
  packages/mason_cli/test/commands/new_test.dart
  packages/mason_cli/test/fixtures/new/hooks/CHANGELOG.md
  packages/mason_cli/test/fixtures/new/hooks/LICENSE
  packages/mason_cli/test/fixtures/new/hooks/README.md
  packages/mason_cli/test/fixtures/new/hooks/__brick__/HELLO.md
  packages/mason_cli/test/fixtures/new/hooks/brick.yaml
  packages/mason_cli/test/fixtures/new/hooks/hooks/.gitignore
  packages/mason_cli/test/fixtures/new/hooks/hooks/post_gen.dart
  packages/mason_cli/test/fixtures/new/hooks/hooks/pre_gen.dart
  packages/mason_cli/test/fixtures/new/hooks/hooks/pubspec.yaml
Labels: enhancement

#331 chore(mason_cli): v0.1.0-dev.21
  packages/mason_cli/CHANGELOG.md
  packages/mason_cli/README.md
  packages/mason_cli/lib/src/version.dart
  packages/mason_cli/pubspec.yaml
Labels: chore

#237 feat(mason): lambda shortcuts
  packages/mason/lib/src/render.dart
  packages/mason/test/src/render_test.dart
Labels: enhancement

#333 chore(mason): use mason_logger ^0.1.0-dev.8
  packages/mason/pubspec.yaml
Labels: chore

#334 chore(mason): v0.1.0-dev.15
  packages/mason/CHANGELOG.md
  packages/mason/lib/src/version.dart
  packages/mason/pubspec.yaml
Labels: chore

#335 chore(mason_cli): v0.1.0-dev.22
  bricks/widget/__brick__/{{name.snakeCase()}}.dart
  packages/mason_cli/CHANGELOG.md
  packages/mason_cli/lib/src/version.dart
  packages/mason_cli/pubspec.yaml
Labels: chore

#336 feat(vscode): create extension
  .github/workflows/vscode.yaml
  extensions/vscode/.eslintrc.json
  extensions/vscode/.gitignore
  extensions/vscode/.vscode/extensions.json
  extensions/vscode/.vscode/launch.json
  extensions/vscode/.vscode/settings.json
  extensions/vscode/.vscode/tasks.json
  extensions/vscode/.vscodeignore
  extensions/vscode/CHANGELOG.md
  extensions/vscode/LICENSE
  extensions/vscode/README.md
  extensions/vscode/assets/logo.png
  extensions/vscode/package-lock.json
  extensions/vscode/package.json
  extensions/vscode/src/events/index.ts
  extensions/vscode/src/events/on-file-saved.ts
  extensions/vscode/src/extension.ts
  extensions/vscode/src/mason/index.ts
  extensions/vscode/src/mason/is-mason-installed.ts
  extensions/vscode/src/mason/mason-get.ts
  extensions/vscode/src/utils/exec.ts
  extensions/vscode/src/utils/index.ts
  extensions/vscode/tsconfig.json
  extensions/vscode/webpack.config.js
Labels: vscode

#338 chore(mason): v0.1.0-dev.16
  packages/mason/CHANGELOG.md
  packages/mason/lib/src/version.dart
  packages/mason/pubspec.yaml
Labels: chore

#341 chore(mason): v0.1.0-dev.17
  packages/mason/CHANGELOG.md
  packages/mason/lib/src/version.dart
  packages/mason/pubspec.yaml
Labels: chore

#344 fix(mason): HookContext vars mutation
  bricks/random_color/hooks/pre_gen.dart
  packages/mason/lib/src/hooks.dart
Labels: bug

#345 chore(mason): v0.1.0-dev.18
  packages/mason/CHANGELOG.md
  packages/mason/lib/src/version.dart
  packages/mason/pubspec.yaml
Labels: chore

#346 feat(widget): simplify widget brick to use SizedBox
  bricks/widget/__brick__/{{name.snakeCase()}}.dart
Labels: enhancement

#347 refactor(mason): improve brick location serialization
  packages/mason/lib/src/mason_yaml.dart
  packages/mason_cli/test/fixtures/add/widget/cat.dart
  packages/mason_cli/test/fixtures/init/mason-lock.json
  packages/mason_cli/test/fixtures/make/widget/my_widget.dart
Labels: refactor

#348 chore(mason): v0.1.0-dev.19
  packages/mason/CHANGELOG.md
  packages/mason/lib/src/version.dart
  packages/mason/pubspec.yaml
Labels: chore
