Repository felangel/mason, pull requests merged in 2022-07, with the labels that each got.

#435 feat(mason_logger): `Progress.update`
  packages/mason_logger/example/main.dart
  packages/mason_logger/lib/src/progress.dart
  packages/mason_logger/test/src/mason_logger_test.dart
  packages/mason_logger/test/src/progress_test.dart
Labels: enhancement

#438 chore(mason_logger): v0.1.0-dev.14
  packages/mason_logger/CHANGELOG.md
  packages/mason_logger/README.md
  packages/mason_logger/example/main.dart
  packages/mason_logger/pubspec.yaml
Labels: chore

#439 chore(mason): v0.1.0-dev.27
  packages/mason/CHANGELOG.md
  packages/mason/lib/src/version.dart
  packages/mason/pubspec.yaml
Labels: chore

#443 fix(mason): override toString on MasonException
  packages/mason/lib/src/exception.dart
  packages/mason/test/src/exception_test.dart
Labels: bug

#444 chore(mason): v0.1.0-dev.28
  packages/mason/CHANGELOG.md
  packages/mason/lib/src/version.dart
  packages/mason/pubspec.yaml
Labels: chore

#445 chore: use pubspec_overrides.yaml
  packages/mason/pubspec.yaml
  packages/mason/pubspec_overrides.yaml
  packages/mason_cli/pubspec.yaml
  packages/mason_cli/pubspec_overrides.yaml
Labels: chore

#453 docs(mason_cli): fix app_icon link in README
  packages/mason_cli/README.md
Labels: documentation

#456 refactor(mason): use mason_logger ^0.1.0
  bricks/random_color/hooks/pre_gen.dart
  packages/mason/pubspec.yaml
Labels: refactor

#454 perf(mason): speed up hooks execution by removing unnecessary file read
  packages/mason/lib/src/hooks.dart
Labels: enhancement

#452 fix: flexible lambda shorthand syntax
  packages/mason/lib/src/render.dart
  packages/mason/test/src/render_test.dart
Labels: bug

#457 chore(mason): v0.1.0-dev.29
  packages/mason/CHANGELOG.md
  packages/mason/lib/src/version.dart
  packages/mason/pubspec.yaml
Labels: chore

#458 refactor(mason_cli): use mason: ^0.1.0-dev.29
  packages/mason_cli/lib/src/commands/bundle.dart
  packages/mason_cli/lib/src/commands/init.dart
  packages/mason_cli/lib/src/commands/make.dart
  packages/mason_cli/lib/src/commands/new.dart
  packages/mason_cli/lib/src/commands/publish.dart
  packages/mason_cli/lib/src/commands/search.dart
  packages/mason_cli/lib/src/commands/unbundle.dart
  packages/mason_cli/pubspec.yaml
  packages/mason_cli/test/commands/bundle_test.dart
  packages/mason_cli/test/commands/new_test.dart
  packages/mason_cli/test/commands/publish_test.dart
  packages/mason_cli/test/commands/search_test.dart
  packages/mason_cli/test/commands/unbundle_test.dart
Labels: refactor

#459 chore(mason_cli): v0.1.0-dev.31
  packages/mason_cli/CHANGELOG.md
  packages/mason_cli/lib/src/version.dart
  packages/mason_cli/pubspec.yaml
Labels: chore

#460 docs(mason_logger): fix typo in README snippet
  packages/mason_logger/README.md
Labels: documentation

#465 refactor(mason_logger): remove pkg:universal_io
  packages/mason_logger/lib/src/io.dart
  packages/mason_logger/lib/src/mason_logger.dart
  packages/mason_logger/lib/src/progress.dart
  packages/mason_logger/pubspec.yaml
  packages/mason_logger/test/src/mason_logger_test.dart
  packages/mason_logger/test/src/progress_test.dart
  packages/mason_logger/test/src/stdio_overrides_test.dart
Labels: refactor

#466 refactor(mason): remove pkg:universal_io
  packages/mason/lib/src/bricks_json.dart
  packages/mason/lib/src/bundler.dart
  packages/mason/lib/src/generator.dart
  packages/mason/lib/src/git.dart
  packages/mason/lib/src/mason_yaml.dart
  packages/mason/pubspec.yaml
  packages/mason/test/src/bricks_json_test.dart
  packages/mason/test/src/bundler_test.dart
  packages/mason/test/src/generator_test.dart
  packages/mason/test/src/git_test.dart
  packages/mason/test/src/mason_yaml_test.dart
Labels: refactor

#467 refactor(mason_api): remove pkg:universal_io
  packages/mason_api/lib/src/mason_api.dart
  packages/mason_api/pubspec.yaml
  packages/mason_api/test/src/mason_api_test.dart
Labels: refactor

#468 refactor(mason_cli): remove pkg:universal_io
  packages/mason_cli/bin/mason.dart
  packages/mason_cli/lib/src/command.dart
  packages/mason_cli/lib/src/command_runner.dart
  packages/mason_cli/lib/src/commands/add.dart
  packages/mason_cli/lib/src/commands/bundle.dart
  packages/mason_cli/lib/src/commands/make.dart
  packages/mason_cli/lib/src/commands/new.dart
  packages/mason_cli/lib/src/commands/publish.dart
  packages/mason_cli/lib/src/commands/unbundle.dart
  packages/mason_cli/pubspec.yaml
  packages/mason_cli/test/commands/add_test.dart
  packages/mason_cli/test/commands/bundle_test.dart
  packages/mason_cli/test/commands/cache_test.dart
  packages/mason_cli/test/commands/get_test.dart
  packages/mason_cli/test/commands/init_test.dart
  packages/mason_cli/test/commands/list_test.dart
  packages/mason_cli/test/commands/make_test.dart
  packages/mason_cli/test/commands/new_test.dart
  packages/mason_cli/test/commands/publish_test.dart
  packages/mason_cli/test/commands/remove_test.dart
  packages/mason_cli/test/commands/unbundle_test.dart
  packages/mason_cli/test/commands/update_test.dart
  packages/mason_cli/test/commands/upgrade_test.dart
  packages/mason_cli/test/helpers/directories_deep_equal.dart
  packages/mason_cli/test/helpers/set_up_testing_environment.dart
  packages/mason_cli/test/mason_generator_test.dart
  packages/mason_cli/test/src/command_test.dart
Labels: refactor

#469 refactor(mason_logger): internal consistency and renaming
  packages/mason_logger/lib/src/mason_logger.dart
  packages/mason_logger/lib/src/progress.dart
Labels: refactor

#470 chore(mason_logger): v0.1.1
  packages/mason_logger/CHANGELOG.md
  packages/mason_logger/pubspec.yaml
Labels: chore

#471 chore(mason_api): v0.1.0-dev.6
  packages/mason_api/CHANGELOG.md
  packages/mason_api/pubspec.yaml
Labels: chore

#472 chore(mason): v0.1.0-dev.30
  packages/mason/CHANGELOG.md
  packages/mason/README.md
  packages/mason/lib/src/version.dart
  packages/mason/pubspec.yaml
Labels: chore

#473 chore(mason_cli): v0.1.0-dev.32
  packages/mason_cli/CHANGELOG.md
  packages/mason_cli/lib/src/version.dart
  packages/mason_cli/pubspec.yaml
Labels: chore

#475 fix(mason): render asymmetrical shorthand lambda expressions correctly
  packages/mason/lib/src/render.dart
  packages/mason/test/src/render_test.dart
Labels: bug

#477 chore(mason): v0.1.0-dev.31
  packages/mason/CHANGELOG.md
  packages/mason/lib/src/version.dart
  packages/mason/pubspec.yaml
Labels: chore
