Repository felangel/mason, pull requests merged in 2022-06, with the labels that each got.

#376 feat(mason_logger): add chooseOne
  packages/mason_logger/example/main.dart
  packages/mason_logger/lib/src/mason_logger.dart
  packages/mason_logger/test/src/mason_logger_test.dart
Labels: enhancement

#383 chore(mason_logger): v0.1.0-dev.10
  packages/mason_logger/CHANGELOG.md
  packages/mason_logger/README.md
  packages/mason_logger/pubspec.yaml
Labels: chore

#381 feat: mason search
  .github/workflows/mason_cli.yaml
  packages/mason_api/lib/mason_api.dart
  packages/mason_api/lib/src/mason_api.dart
  packages/mason_api/lib/src/models/brick_search_result.dart
  packages/mason_api/lib/src/models/brick_search_result.g.dart
  packages/mason_api/lib/src/models/models.dart
  packages/mason_api/test/src/mason_api_test.dart
  packages/mason_cli/lib/src/command_runner.dart
  packages/mason_cli/lib/src/commands/commands.dart
  packages/mason_cli/lib/src/commands/search.dart
  packages/mason_cli/test/commands/search_test.dart
  packages/mason_cli/test/src/command_runner_test.dart
Labels: enhancement

#386 chore(mason_api): v0.1.0-dev.5
  packages/mason_api/CHANGELOG.md
  packages/mason_api/pubspec.yaml
Labels: chore

#387 chore(mason_cli): v0.1.0-dev.27
  .github/workflows/mason_cli.yaml
  packages/mason_cli/CHANGELOG.md
  packages/mason_cli/README.md
  packages/mason_cli/lib/src/version.dart
  packages/mason_cli/pubspec.yaml
Labels: chore

#389 feat(mason_cli): support enum vars
  .github/workflows/mason_cli.yaml
  packages/mason_cli/lib/src/commands/make.dart
  packages/mason_cli/lib/src/commands/new.dart
  packages/mason_cli/test/bricks/enum_no_choices/__brick__/.gitkeep
  packages/mason_cli/test/bricks/enum_no_choices/brick.yaml
  packages/mason_cli/test/commands/make_test.dart
  packages/mason_cli/test/fixtures/make/favorite_color/color.md
  packages/mason_cli/test/fixtures/make/mason.yaml
  packages/mason_cli/test/fixtures/new/custom/bricks/hello_world/brick.yaml
  packages/mason_cli/test/fixtures/new/hooks/brick.yaml
  packages/mason_cli/test/fixtures/new/simple/hello_world/brick.yaml
Labels: enhancement

#390 fix(mason): do not prompt when overwrite rule is alwaysOverwrite
  packages/mason/lib/src/generator.dart
  packages/mason/test/src/generator_test.dart
Labels: bug

#392 chore(mason_cli): v0.1.0-dev.28
  .github/workflows/mason_cli.yaml
  packages/mason_cli/CHANGELOG.md
  packages/mason_cli/README.md
  packages/mason_cli/lib/src/version.dart
  packages/mason_cli/pubspec.yaml
Labels: chore

#393 fix(mason_logger): err should write to `stderr`
  packages/mason_logger/lib/src/mason_logger.dart
  packages/mason_logger/lib/src/progress.dart
  packages/mason_logger/test/src/mason_logger_test.dart
  packages/mason_logger/test/src/progress_test.dart
Labels: bug

#395 chore(mason_logger): v0.1.0-dev.11
  packages/mason_logger/CHANGELOG.md
  packages/mason_logger/pubspec.yaml
Labels: chore

#396 chore(mason_logger): upgrade to mocktail ^0.3.0
  packages/mason_logger/pubspec.yaml
Labels: chore

#399 feat(mason_logger): chooseAny support
  packages/mason_logger/README.md
  packages/mason_logger/example/main.dart
  packages/mason_logger/lib/src/mason_logger.dart
  packages/mason_logger/test/src/mason_logger_test.dart
Labels: enhancement

#400 fix(mason_logger): choose api windows compatibility
  packages/mason_logger/lib/src/mason_logger.dart
  packages/mason_logger/test/src/mason_logger_test.dart
Labels: bug, enhancement

#401 chore(mason_logger): v0.1.0-dev.12
  packages/mason_logger/CHANGELOG.md
  packages/mason_logger/pubspec.yaml
Labels: chore

#404 feat(mason): support array var type in brick.yaml
  packages/mason/lib/src/brick_yaml.dart
  packages/mason/lib/src/brick_yaml.g.dart
  packages/mason/pubspec.yaml
  packages/mason/test/src/brick_yaml_test.dart
Labels: enhancement

#405 fix(mason): file path looping array resolution
  packages/mason/lib/src/generator.dart
  packages/mason/test/bricks/loop/__brick__/main_{{#values}}{{{.}}}{{/values}}.txt
  packages/mason/test/bricks/loop/brick.yaml
  packages/mason/test/src/generator_test.dart
Labels: bug

#406 chore(mason): v0.1.0-dev.26
  packages/mason/CHANGELOG.md
  packages/mason/lib/src/version.dart
  packages/mason/pubspec.yaml
Labels: chore

#407 feat(mason_cli): support array vars
  packages/mason_cli/lib/src/commands/make.dart
  packages/mason_cli/pubspec.yaml
  packages/mason_cli/test/bricks/array_no_choices/__brick__/.gitkeep
  packages/mason_cli/test/bricks/array_no_choices/brick.yaml
  packages/mason_cli/test/commands/make_test.dart
  packages/mason_cli/test/fixtures/make/flavors/README.md
  packages/mason_cli/test/fixtures/make/flavors/main_development.dart
  packages/mason_cli/test/fixtures/make/flavors/main_production.dart
  packages/mason_cli/test/fixtures/make/mason.yaml
Labels: enhancement

#408 feat(mason_cli): bump minimum mason version in new bricks
  packages/mason_cli/README.md
  packages/mason_cli/lib/src/commands/new.dart
  packages/mason_cli/test/commands/get_test.dart
  packages/mason_cli/test/commands/make_test.dart
  packages/mason_cli/test/fixtures/new/custom/bricks/hello_world/brick.yaml
  packages/mason_cli/test/fixtures/new/hooks/brick.yaml
  packages/mason_cli/test/fixtures/new/simple/hello_world/brick.yaml
Labels: enhancement

#409 chore(mason_cli): v0.1.0-dev.29
  packages/mason_cli/CHANGELOG.md
  packages/mason_cli/lib/src/version.dart
  packages/mason_cli/pubspec.yaml
Labels: chore

#415 chore(mason_logger): v0.1.0-dev.13
  packages/mason_logger/CHANGELOG.md
  packages/mason_logger/pubspec.yaml
Labels: chore

#411 feat(vscode): add make command
  extensions/vscode/package-lock.json
  extensions/vscode/package.json
  extensions/vscode/src/commands/add-brick.ts
  extensions/vscode/src/commands/index.ts
  extensions/vscode/src/commands/init.ts
  extensions/vscode/src/commands/make-brick.ts
  extensions/vscode/src/commands/remove-brick.ts
  extensions/vscode/src/extension.ts
  extensions/vscode/src/mason/get-brick-yaml.ts
  extensions/vscode/src/mason/index.ts
  extensions/vscode/src/mason/mason-make.ts
  extensions/vscode/src/mason/mason-remove.ts
Labels: enhancement, vscode

#416 feat(mason_cli): support bundling git and hosted bricks
  .gitignore
  packages/mason_cli/lib/src/commands/bundle.dart
  packages/mason_cli/test/commands/bundle_test.dart
Labels: enhancement

#418 chore(mason_cli): v0.1.0-dev.30
  packages/mason_cli/CHANGELOG.md
  packages/mason_cli/README.md
  packages/mason_cli/lib/src/version.dart
  packages/mason_cli/pubspec.yaml
Labels: chore

#421 feat(vscode): make global brick
  extensions/vscode/package.json
  extensions/vscode/src/commands/make-brick.ts
  extensions/vscode/src/extension.ts
Labels: enhancement, vscode

#422 feat(vscode): mason make support hooks
  extensions/vscode/src/commands/make-brick.ts
  extensions/vscode/src/mason/mason-exec.ts
  extensions/vscode/src/mason/mason-make.ts
Labels: enhancement, vscode

#423 chore(vscode): v0.1.2
  extensions/vscode/CHANGELOG.md
  extensions/vscode/README.md
  extensions/vscode/package-lock.json
  extensions/vscode/package.json
Labels: chore, vscode

#424 fix(vscode): add make commands to activationEvents
  extensions/vscode/package.json
Labels: bug, vscode

#425 chore(vscode): v0.1.3
  extensions/vscode/CHANGELOG.md
  extensions/vscode/package-lock.json
  extensions/vscode/package.json
Labels: chore, vscode

#427 fix(vscode): make supports spaces in string vars
  extensions/vscode/src/commands/make-brick.ts
Labels: bug, vscode

#428 chore(vscode): v0.1.4
  extensions/vscode/CHANGELOG.md
  extensions/vscode/package-lock.json
  extensions/vscode/package.json
Labels: chore, vscode

#437 ci: use semantic_pull_request workflow
  .github/workflows/ci.yaml
Labels: ci

#436 perf(mason): run substitutions in isolate and improve render specificity
  packages/mason/lib/src/generator.dart
Labels: performance
