Repository felangel/mason, pull requests merged in 2022-10, with the labels that each got.

#533 fix(mason_api): login sets in-memory credentials
  packages/mason_api/lib/src/mason_api.dart
  packages/mason_api/test/src/mason_api_test.dart
Labels: bug

#534 chore(mason_api): v0.1.0-dev.8
  packages/mason_api/CHANGELOG.md
  packages/mason_api/pubspec.yaml
Labels: chore

#537 feat(mason_cli): add <brick> <version>
  packages/mason_cli/lib/src/commands/add.dart
  packages/mason_cli/test/commands/add_test.dart
Labels: enhancement

#538 chore(mason_cli): v0.1.0-dev.36
  packages/mason_cli/CHANGELOG.md
  packages/mason_cli/lib/src/version.dart
  packages/mason_cli/pubspec.yaml
Labels: chore

#478 feat(mason_logger): add ProgressOptions API
  packages/mason_logger/lib/mason_logger.dart
  packages/mason_logger/lib/src/mason_logger.dart
  packages/mason_logger/lib/src/progress.dart
  packages/mason_logger/test/src/mason_logger_test.dart
  packages/mason_logger/test/src/progress_test.dart
Labels: enhancement

#540 chore(mason_logger): v0.1.4
  packages/mason_logger/CHANGELOG.md
  packages/mason_logger/LICENSE
  packages/mason_logger/pubspec.yaml
Labels: chore

#539 feat(mason_logger): generic support for `chooseOne` and `chooseAny`
  packages/mason_cli/test/commands/make_test.dart
  packages/mason_logger/example/main.dart
  packages/mason_logger/lib/src/mason_logger.dart
  packages/mason_logger/test/src/mason_logger_test.dart
Labels: enhancement

#542 chore(mason_logger): v0.2.0
  packages/mason_logger/CHANGELOG.md
  packages/mason_logger/example/main.dart
  packages/mason_logger/pubspec.yaml
  packages/mason_logger/test/src/mason_logger_test.dart
Labels: chore

#543 chore(mason): v0.1.0-dev.34
  packages/mason/CHANGELOG.md
  packages/mason/LICENSE
  packages/mason/lib/src/version.dart
  packages/mason/pubspec.yaml
Labels: chore

#541 feat(mason_cli): support mason upgrade --global
  packages/mason_cli/lib/src/command.dart
  packages/mason_cli/lib/src/commands/add.dart
  packages/mason_cli/lib/src/commands/init.dart
  packages/mason_cli/lib/src/commands/remove.dart
  packages/mason_cli/lib/src/commands/upgrade.dart
  packages/mason_cli/lib/src/install_brick.dart
  packages/mason_cli/test/commands/add_test.dart
  packages/mason_cli/test/commands/upgrade_test.dart
  packages/mason_cli/test/fixtures/make/flavors/main_development.dart
  packages/mason_cli/test/fixtures/make/flavors/main_production.dart
Labels: enhancement

#544 chore(mason_cli): upgrade deps
  packages/mason_cli/pubspec.yaml
Labels: chore

#545 chore(mason_cli): v0.1.0-dev.37
  packages/mason_cli/CHANGELOG.md
  packages/mason_cli/LICENSE
  packages/mason_cli/README.md
  packages/mason_cli/lib/src/version.dart
  packages/mason_cli/pubspec.yaml
Labels: chore

#568 chore(mason_logger): v0.2.1
  packages/mason_logger/CHANGELOG.md
  packages/mason_logger/pubspec.yaml
Labels: chore

#581 perf(mason)!: avoid templating hook contents
  bricks/hooks/hooks/post_gen.dart
  bricks/hooks/hooks/pre_gen.dart
  packages/mason/lib/src/hooks.dart
  packages/mason/test/bundles/hooks_bundle.dart
  packages/mason/test/src/bundler_test.dart
  packages/mason/test/src/generator_test.dart
  packages/mason_cli/test/bundles/hooks_bundle.dart
  packages/mason_cli/test/commands/bundle_test.dart
Labels: breaking change, performance
