Repository felangel/mason, pull requests merged in 2022-08, with the labels that each got.

#487 feat(mason_cli): disable lints in dart bundles
  packages/mason_cli/lib/src/commands/bundle.dart
  packages/mason_cli/test/bundles/greeting_bundle.dart
  packages/mason_cli/test/bundles/hooks_bundle.dart
  packages/mason_cli/test/bundles/legacy_greeting_bundle.dart
  packages/mason_cli/test/commands/bundle_test.dart
Labels: enhancement

#488 chore(mason_cli): v0.1.0-dev.33
  packages/mason_cli/CHANGELOG.md
  packages/mason_cli/lib/src/version.dart
  packages/mason_cli/pubspec.yaml
Labels: chore

#481 feat(mason_api): add close
  .github/workflows/mason_cli.yaml
  packages/mason_api/example/main.dart
  packages/mason_api/lib/src/mason_api.dart
  packages/mason_api/test/src/mason_api_test.dart
  packages/mason_cli/lib/src/command_runner.dart
  packages/mason_cli/test/src/command_runner_test.dart
Labels: enhancement

#489 chore(mason_api): upgrade to mocktail ^0.3.0
  packages/mason_api/pubspec.yaml
  packages/mason_api/test/src/mason_api_test.dart
Labels: chore

#490 chore(mason_api): v0.1.0-dev.7
  packages/mason_api/CHANGELOG.md
  packages/mason_api/pubspec.yaml
Labels: chore

#491 chore(mason_cli): upgrade to mason_api ^0.1.0-dev.7
  .github/workflows/mason_cli.yaml
  packages/mason_cli/pubspec.yaml
Labels: chore

#492 chore(mason_cli): v0.1.0-dev.34
  packages/mason_cli/CHANGELOG.md
  packages/mason_cli/lib/src/version.dart
  packages/mason_cli/pubspec.yaml
Labels: chore

#493 fix(vscode): assume enum default prompt value
  extensions/vscode/src/commands/make-brick.ts
Labels: bug, vscode

#495 chore(vscode): v0.1.5
  extensions/vscode/CHANGELOG.md
  extensions/vscode/package-lock.json
  extensions/vscode/package.json
Labels: chore, vscode

#494 feat(logger): adds support for milliseconds on progress duration
  packages/mason_logger/lib/src/progress.dart
  packages/mason_logger/test/src/progress_test.dart
Labels: enhancement

#497 chore(mason_logger): v0.1.2
  packages/mason_logger/CHANGELOG.md
  packages/mason_logger/pubspec.yaml
Labels: chore
