Repository felangel/mason, pull requests merged in 2023-04, with the labels that each got.

#840 feat: integrate `recase` and include `pascalDotCase`
  packages/mason/lib/src/recase.dart
  packages/mason/lib/src/render.dart
  packages/mason/lib/src/string_case_extensions.dart
  packages/mason/pubspec.yaml
  packages/mason/test/src/render_test.dart
  packages/mason/test/src/string_case_extensions_test.dart
  packages/mason_cli/README.md
Labels: enhancement

#807 docs(mason_cli): add `README.zh.md`
  packages/mason_cli/README.md
  packages/mason_cli/README.zh.md
Labels: documentation

#855 chore(mason): v0.1.0-dev.49
  packages/mason/CHANGELOG.md
  packages/mason/lib/src/version.dart
  packages/mason/pubspec.yaml
  packages/mason_cli/test/fixtures/new/custom/bricks/hello_world/brick.yaml
  packages/mason_cli/test/fixtures/new/hooks/brick.yaml
  packages/mason_cli/test/fixtures/new/hooks/hooks/pubspec.yaml
  packages/mason_cli/test/fixtures/new/simple/hello_world/brick.yaml
Labels: chore
