Repository felangel/mason, pull requests merged in 2023-02, with the labels that each got.

#729 fix(mason_cli): update silent failures
  packages/mason_cli/lib/src/commands/update.dart
  packages/mason_cli/pubspec.yaml
  packages/mason_cli/test/commands/update_test.dart
Labels: bug

#732 chore(mason_cli): v0.1.0-dev.44
  packages/mason_cli/CHANGELOG.md
  packages/mason_cli/lib/src/version.dart
  packages/mason_cli/pubspec.yaml
Labels: chore

#734 fix(vscode): support spaces in mason make `--output-dir`
  extensions/vscode/src/mason/mason-make.ts
Labels: bug, vscode

#735 chore(vscode): v0.1.8
  extensions/vscode/CHANGELOG.md
  extensions/vscode/package-lock.json
  extensions/vscode/package.json
Labels: chore

#745 chore(deps): upgrade to very_good_analysis ^4.0.0
  packages/mason/analysis_options.yaml
  packages/mason/lib/mason.dart
  packages/mason/lib/src/brick.dart
  packages/mason/lib/src/brick_yaml.dart
  packages/mason/pubspec.yaml
  packages/mason_api/analysis_options.yaml
  packages/mason_api/lib/mason_api.dart
  packages/mason_api/pubspec.yaml
  packages/mason_cli/analysis_options.yaml
  packages/mason_cli/lib/mason_cli.dart
  packages/mason_cli/lib/src/commands/search.dart
  packages/mason_cli/pubspec.yaml
  packages/mason_cli/test/ensure_build_test.dart
  packages/mason_logger/analysis_options.yaml
  packages/mason_logger/lib/mason_logger.dart
  packages/mason_logger/pubspec.yaml
Labels: chore, dependencies

#733 feat(mason_cli): add `--quiet` flag to `make` command
  packages/mason/lib/src/generator.dart
  packages/mason/test/src/generator_test.dart
  packages/mason_cli/lib/src/commands/make.dart
  packages/mason_cli/test/commands/make_test.dart
Labels: enhancement

#746 refactor: use `super.key`
  bricks/widget/__brick__/{{name.snakeCase()}}.dart
  packages/mason_cli/test/fixtures/add/widget/cat.dart
  packages/mason_cli/test/fixtures/install/widget/cat.dart
  packages/mason_cli/test/fixtures/make/widget/my_widget.dart
Labels: refactor

#753 chore(mason_api): v0.1.0-dev.10
  packages/mason_api/CHANGELOG.md
  packages/mason_api/pubspec.yaml
Labels: chore

#754 chore(mason_logger): v0.2.5
  packages/mason_logger/CHANGELOG.md
  packages/mason_logger/pubspec.yaml
Labels: chore

#755 chore(mason): v0.1.0-dev.42
  packages/mason/CHANGELOG.md
  packages/mason/lib/src/version.dart
  packages/mason/pubspec.yaml
  packages/mason_cli/pubspec.yaml
  packages/mason_cli/test/fixtures/new/custom/bricks/hello_world/brick.yaml
  packages/mason_cli/test/fixtures/new/hooks/brick.yaml
  packages/mason_cli/test/fixtures/new/hooks/hooks/pubspec.yaml
  packages/mason_cli/test/fixtures/new/simple/hello_world/brick.yaml
Labels: chore

#756 chore(mason_cli): v0.1.0-dev.45
  packages/mason_cli/CHANGELOG.md
  packages/mason_cli/lib/src/version.dart
  packages/mason_cli/pubspec.yaml
Labels: chore

#750 fix(mason_cli): brick installation algorithm
  packages/mason/lib/src/bricks_json.dart
  packages/mason/test/src/bricks_json_test.dart
  packages/mason_cli/lib/src/install_brick.dart
  packages/mason_cli/test/commands/get_test.dart
  packages/mason_cli/test/commands/make_test.dart
Labels: bug

#763 chore(mason): v0.1.0-dev.43
  packages/mason/CHANGELOG.md
  packages/mason/lib/src/version.dart
  packages/mason/pubspec.yaml
  packages/mason_cli/test/fixtures/new/custom/bricks/hello_world/brick.yaml
  packages/mason_cli/test/fixtures/new/hooks/brick.yaml
  packages/mason_cli/test/fixtures/new/hooks/hooks/pubspec.yaml
  packages/mason_cli/test/fixtures/new/simple/hello_world/brick.yaml
Labels: chore

#764 chore(mason_cli): v0.1.0-dev.46
  packages/mason_cli/CHANGELOG.md
  packages/mason_cli/lib/src/version.dart
  packages/mason_cli/pubspec.yaml
Labels: chore

#765 chore(vscode): v0.1.9
  extensions/vscode/CHANGELOG.md
  extensions/vscode/package-lock.json
  extensions/vscode/package.json
Labels: chore

#766 chore(mason): v0.1.0-dev.44
  packages/mason/CHANGELOG.md
  packages/mason/lib/src/version.dart
  packages/mason/pubspec.yaml
  packages/mason_cli/pubspec.yaml
  packages/mason_cli/test/fixtures/new/custom/bricks/hello_world/brick.yaml
  packages/mason_cli/test/fixtures/new/hooks/brick.yaml
  packages/mason_cli/test/fixtures/new/hooks/hooks/pubspec.yaml
  packages/mason_cli/test/fixtures/new/simple/hello_world/brick.yaml
Labels: chore

#767 feat(mason_cli): add repository field and README updates to new brick
  .github/workflows/mason_cli.yaml
  packages/mason_cli/lib/src/commands/new.dart
  packages/mason_cli/test/fixtures/new/custom/bricks/hello_world/README.md
  packages/mason_cli/test/fixtures/new/custom/bricks/hello_world/brick.yaml
  packages/mason_cli/test/fixtures/new/hooks/README.md
  packages/mason_cli/test/fixtures/new/hooks/brick.yaml
  packages/mason_cli/test/fixtures/new/simple/hello_world/README.md
  packages/mason_cli/test/fixtures/new/simple/hello_world/brick.yaml
Labels: enhancement

#769 feat(mason): add `publishTo` to `MasonBundle`
  packages/mason/lib/src/bundler.dart
  packages/mason/lib/src/mason_bundle.dart
  packages/mason/lib/src/mason_bundle.g.dart
  packages/mason/test/bricks/custom_registry/brick.yaml
  packages/mason/test/bricks/no_registry/brick.yaml
  packages/mason/test/src/bundler_test.dart
  packages/mason/test/src/mason_bundle_test.dart
Labels: enhancement

#770 chore(mason): v0.1.0-dev.45
  packages/mason/CHANGELOG.md
  packages/mason/lib/src/version.dart
  packages/mason/pubspec.yaml
  packages/mason_cli/pubspec.yaml
  packages/mason_cli/test/fixtures/new/custom/bricks/hello_world/brick.yaml
  packages/mason_cli/test/fixtures/new/hooks/brick.yaml
  packages/mason_cli/test/fixtures/new/hooks/hooks/pubspec.yaml
  packages/mason_cli/test/fixtures/new/simple/hello_world/brick.yaml
Labels: chore

#768 chore(mason_cli): v0.1.0-dev.47
  packages/mason_cli/CHANGELOG.md
  packages/mason_cli/README.md
  packages/mason_cli/lib/src/version.dart
  packages/mason_cli/pubspec.yaml
Labels: chore

#774 feat(vscode): support mason new brick
  extensions/vscode/README.md
  extensions/vscode/package.json
  extensions/vscode/src/commands/index.ts
  extensions/vscode/src/commands/make-brick.ts
  extensions/vscode/src/commands/new-brick.ts
  extensions/vscode/src/extension.ts
  extensions/vscode/src/mason/index.ts
  extensions/vscode/src/mason/mason-new.ts
  extensions/vscode/src/utils/index.ts
  extensions/vscode/src/utils/prompt-for-target-directory.ts
Labels: enhancement

#775 chore(vscode): v0.1.10
  extensions/vscode/CHANGELOG.md
  extensions/vscode/package-lock.json
  extensions/vscode/package.json
Labels: chore

#776 feat(mason_cli): add `--force` and `--dry-run` to `publish` command
  packages/mason_cli/lib/src/commands/publish.dart
  packages/mason_cli/test/commands/publish_test.dart
Labels: enhancement

#777 chore(mason_cli): v0.1.0-dev.48
  packages/mason_cli/CHANGELOG.md
  packages/mason_cli/lib/src/version.dart
  packages/mason_cli/pubspec.yaml
Labels: chore

#782 refactor(mason_cli): mason add uses build instead of compile
  packages/mason_cli/lib/src/commands/add.dart
Labels: refactor

#783 ci: concurrency cancel in progress jobs
  .github/workflows/ci.yaml
  .github/workflows/mason.yaml
  .github/workflows/mason_api.yaml
  .github/workflows/mason_cli.yaml
  .github/workflows/mason_logger.yaml
  .github/workflows/vscode.yaml
Labels: ci

#784 refactor(mason_cli): streamline stdout from mason bundle
  packages/mason_cli/lib/src/commands/bundle.dart
  packages/mason_cli/test/commands/bundle_test.dart
Labels: refactor

#785 refactor: use private mocks
  packages/mason/test/src/generator_test.dart
  packages/mason_cli/test/commands/add_test.dart
  packages/mason_cli/test/commands/bundle_test.dart
  packages/mason_cli/test/commands/cache_test.dart
  packages/mason_cli/test/commands/get_test.dart
  packages/mason_cli/test/commands/init_test.dart
  packages/mason_cli/test/commands/list_test.dart
  packages/mason_cli/test/commands/login_test.dart
  packages/mason_cli/test/commands/logout_test.dart
  packages/mason_cli/test/commands/make_test.dart
  packages/mason_cli/test/commands/new_test.dart
  packages/mason_cli/test/commands/publish_test.dart
  packages/mason_cli/test/commands/remove_test.dart
  packages/mason_cli/test/commands/search_test.dart
  packages/mason_cli/test/commands/unbundle_test.dart
  packages/mason_cli/test/commands/update_test.dart
  packages/mason_cli/test/commands/upgrade_test.dart
  packages/mason_cli/test/mason_generator_test.dart
  packages/mason_cli/test/src/command_runner_test.dart
  packages/mason_cli/test/src/command_test.dart
  packages/mason_logger/test/src/mason_logger_test.dart
  packages/mason_logger/test/src/progress_test.dart
Labels: refactor
