Repository felangel/mason, pull requests merged in 2024-08, with the labels that each got.

#1395 chore(mason_logger): tighten deps
  packages/mason_logger/pubspec.yaml
Labels: chore

#1391 feat(mason_logger): add `interval` to `ProgressAnimation`
  packages/mason_logger/lib/src/progress.dart
  packages/mason_logger/test/src/progress_test.dart
Labels: enhancement

#1396 chore(mason_logger): v0.3.0
  packages/mason_logger/CHANGELOG.md
  packages/mason_logger/pubspec.yaml
Labels: chore

#1411 chore(mason): loosen `pkg:collection` constraint for Flutter compatibility
  packages/mason/pubspec.yaml
Labels: dependencies
